### ISSUE TITLE
License

### ISSUE THREAD

**Issue by o9000** [philer/HTMLpaper#1]
Hi,

I would like to use some of these stylesheets for a report to be displayed on a web site. Basically I will use @media screen to display the text in sans fonts and @media print to use Computer Modern when printing, so that it looks great in both ways and I don't have to make PDFs etc.

I was wondering if you are willing to license them using a standard open source licence such as MIT, Apache, BSD, Gnu GPL, instead of that license text you have there? Basically I have two concerns:
- The statement "If you create something cool with this, show me, so I can feel warm and fuzzy inside." I would prefer not to have to send you a copy of every report I write, especially if it's internal. I would also argue that this makes it a non-open source license as in this aspect it is more prohibitive even than GPL.
- That text is quite ambiguous and could be interpreted by a lawyer in who-knows-what ways, which is not good for me. It's probably not good for you either, since if I make a copy of the project that satisfies all the points (including showing it to you), as your license does not impose any restrictions on re-licensing I could license my project using another license and I am confident this would be perfectly legal.

I'm sure you found it funny to write that text, but in the interest of the open source community it would be best to stick to the regular licenses.

Of course you are free to do whatever you want to your code, but other people like me like it and would like to use it, so I would appreciate it if you reconsider :)

**Comment by philer** [comment]
Well I didn't feel too serious about this since it's essentially just a few CSS rules, but you're right about my vague little statement. I'll add a proper licence when I get home. It'll probably be GPL3. :)

Also I should probably update the font stuff. There is a font called “Latin Modern” which is a much more up-to-date alternative that is available as OpenType on most Linux distros and probably other OSs as well. Apparently that's the font that's actually being used by most LaTeX documents today.

**Comment by o9000** [comment]
OK :) I know it was silly but I always respect the licenses carefully.

I also appreciate the tip about Latin Modern, I didn't know the difference. I will look into it.

Edit: I tried Latin Modern using http://www.fontsquirrel.com/fonts/latin-modern-roman but it's missing some ligatures (has fi, ff but not ffi) compared to CM, in Firefox (Chrome is a disaster). So I'm going to stick with your original CM fonts as they look slightly better and I didn't notice any problem.

**Comment by philer** [comment]
I've added a license (MIT) and updated the fonts to Latin Modern using the OpenType version available on [their website](http://www.gust.org.pl/projects/e-foundry/latin-modern).  By default it'll use a system provided version of Latin Modern and only fall back to the webfont if it's not installed.

I included all the font files in the repository but they aren't all used by the css font-face since it's really a pain to figure all those out (72 font files O.o).

Computer Modern is still included, you have to enable it manually in `latex.css`.

**Comment by o9000** [comment]
A huge THANKS!

**Comment by o9000** [comment]
Just FYI I pusblished my changes here https://gitlab.com/o9000/meta

Thanks again for your work.

**Comment by philer** [comment]
Looks good, glad you could use it :)
